// <auto-generated />
using System;
using Data.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations.LogDb
{
    [DbContext(typeof(LogDbContext))]
    partial class LogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.LogApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("InclusionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Method")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Path")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("QueryString")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TypeLog")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("LogsApplication");
                });
#pragma warning restore 612, 618
        }
    }
}
