// <auto-generated />
using System;
using Data.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations.LogApp
{
    [DbContext(typeof(LogDbContext))]
    [Migration("20240407182741_LogApp")]
    partial class LogApp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.LogApp.LogRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("InclusionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Method")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Path")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("QueryString")
                        .HasColumnType("varchar(120)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<string>("TypeLog")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("InclusionDate")
                        .HasDatabaseName("IX_LogRequests_InclusionDate");

                    b.HasIndex("TypeLog")
                        .HasDatabaseName("IX_LogRequests_TypeLog");

                    b.ToTable("LogRequests", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
